<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'product_name' => 'Chaos Theory #1',
                'series' => 'Chaos Theory',
                'tags' => "'Chaos Theory'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1721705',
                'ejunkie_link_physical' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1770871',
                'publisher_id' => 1,
                'summary' => 'The introductory chapter of Chaos Theory we follow our protagonist by diving into his troubled past and realizing some of the motivation for his relentless pursuit of Donovan Green, owner of Majesty Pharmaceuticals and the architect behind the current state of the world.',
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_chaostheory/covers/Chaos_Theory_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'chaostheory'
            ],
            [
                'product_name' => 'Chaos Theory #2',
                'series' => 'Chaos Theory',
                'tags' => "'Chaos Theory'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1721706',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => 'We are introduced to the Spartan unit, a rebel militia dedicated to protecting the people of the outlands from oppressive Majesty activity. On a “routine” supply run they learn that the current rules of engagement are changing, and now they must adapt on the fly to change with it.',
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_chaostheory/covers/Chaos_Theory_2.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'chaostheory'
            ],
            [
                'product_name' => 'Alexia Midnight #0',
                'series' => 'Alexia Midnight',
                'tags' => "'Alexia Midnight', 'Legends'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1743167',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => 'Alexia Midnight, a newborn vampire must understand what it means to be a vampire with the best teacher of them all; Dracula. Meanwhile, being chased by The Vigor, a religious cult bound to hunt the night.',
                'digital_price' => 1.00,
                'physical_price' => null,
                'img_string' => 'img/series_alexiamidnight/covers/Alexia_Midnight_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'alexiamidnight'
            ],
            [
                'product_name' => 'Armored Eagle #1',
                'series' => 'Armored Eagle',
                'tags' => "'Armored Eagle'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1743177',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "Itzli's conception is no ordinary one as it brings dark secrets around his origin. This series depicts King Itzcoatl and Yaretzi; a slave woman, who are intertwined in a forbidden romance. But when trouble arises the King must choose between his throne or his love. But that is the least of King Itzcoatl's problems.",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/Armored_Eagle1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'Armored Eagle #2',
                'series' => 'Armored Eagle',
                'tags' => "'Armored Eagle'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1743178',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "Over 15 years have passed since the events of the Armored Eagle Issue 1, Itzli and the remaining Aztecs have been forced into hiding. Growing tired of hiding in the shadows of a once great empire, Itzli alone dares to take on the invasive Anunnaki. Will Itzli succeed or will he meet the same fate as those before him?",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/Armored_Eagle2.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'Armored Eagle #3',
                'series' => 'Armored Eagle',
                'tags' => "'Armored Eagle'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1743179',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "How will Itzli fare against the mighty force of the Anunnaki? How will Enki assist the Aztecs in defeating Enlil? The final showdown between Enlil and Itzli starts now!",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/Armored_Eagle3.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'E. O. A #1',
                'series' => 'Elements Of Agony',
                'tags' => "'Elements Of Agony', 'The Final Wielder",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1721708',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "Ka`Jal is called to the scene of a murder which the police think was done by a mythical creature. Stunned due to the treaty, Ka`Jal calls for an emergency meeting demanding an answer. This causes the Mythical Creature Trinity to react violently, while Ka`Jal discovers the truth about her parents.",
                'digital_price' => 2.99,
                'physical_price' => 6.99,
                'img_string' => 'img/series_elementsofagony/covers/EOA_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store-slug' => 'eoa'
            ],
            [
                'product_name' => 'The Final Wielder',
                'series' => 'The Final Wielder',
                'tags' => "'Elements Of Agony', 'The Final Wielder'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1721709',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "While on a dig Charles discovers a magical Amulet created millennia ago that reveals a whole new life to him. This all came with a target being put on his back due to the powers possessed by the amulet, but everything turns for the worst when Charles discovers there's more than 1 Amulet.",
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_finalwielder/covers/Final_Wielder_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'thefinalwielder'
            ],
            [
                'product_name' => 'Lost Dominion #1',
                'series' => 'The Lost Dominion',
                'tags' => "'The Lost Dominion'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1747702',
                'ejunkie_link_physical' => null,
                'publisher_id' => 4,
                'summary' => "On the brink of interstellar war, a group of unlikely allies must join together to reclaim their Lost Dominion.",
                'digital_price' => 4.99,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Lumostation/Lost_Dominion_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'lumostation'
            ],
            [
                'product_name' => 'Lost Dominion #2',
                'series' => 'The Lost Dominion',
                'tags' => "'The Lost Dominion'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1747703',
                'ejunkie_link_physical' => null,
                'publisher_id' => 4,
                'summary' => "Bounty hunter Red-88 tracks inmate Z-IV to Lumo Station.",
                'digital_price' => 4.99,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Lumostation/Lost_Dominion_2.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'lumostation'
            ],
            [
                'product_name' => 'Lost Dominion #3',
                'series' => 'The Lost Dominion',
                'tags' => "'The Lost Dominion'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1747705',
                'ejunkie_link_physical' => null,
                'publisher_id' => 4,
                'summary' => "Looking for a safe harbor, Deven, Tiala, Corrina, and Ziv travel to the mining planet of Hippeia only to find greater dangers await for them!",
                'digital_price' => 4.99,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Lumostation/Lost_Dominion_3.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'lumostation'
            ],
            [
                'product_name' => 'Fracture Point #1',
                'series' => 'Fracture Point',
                'tags' => "'Fracture Point'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1745320',
                'ejunkie_link_physical' => null,
                'publisher_id' => 4,
                'summary' => "Time Agent Harper Wells must sacrifice everything to protect his family, even the timeline!",
                'digital_price' => 1.99,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Lumostation/Fracture_Point_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'lumostation'
            ],
            [
                'product_name' => 'Fracture Point #2',
                'series' => 'Fracture Point',
                'tags' => "'Fracture Point'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1747178',
                'ejunkie_link_physical' => null,
                'publisher_id' => 4,
                'summary' => "When Time Marine Elektra Mitchell goes on a routine mission to stop a Time-Resistance Cell, she is told of a conspiracy that threatens both the past and future of her timeline!",
                'digital_price' => 1.99,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Lumostation/Fracture_Point_2.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'lumostation'
            ],
            [
                'product_name' => 'Moonage #1',
                'series' => 'Moonage',
                'tags' => "'Moonage'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1743182',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "Heartbroken after the disappearance of her mother, Carissa Hinz has to learn how to keep on living as a normal kid. With her father and younger brother by her side, Carissa has not lost hope that one day she will be reunited with her mother, Linda.",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/Moonage_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'Moonage #2',
                'series' => 'Moonage',
                'tags' => "'Moonage'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1743186',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "With a newly found crew, the Zellonian scientists have given Carissa. The crew will have to go to Dragon's Moon and retrieve the Fire Relic. But this will be no easy task as the Dragons are known for their ferocity.",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/Moonage_2.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'Moonage #3',
                'series' => 'Moonage',
                'tags' => "'Moonage'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1752579',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "After months of traveling through space, Carissa and her crew are closing in on the right wormhole that will send them back to Earth.",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/Moonage_3.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'The Sergeant #1',
                'series' => 'The Sergeant',
                'tags' => "'The Sergeant'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1743180',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "After the Chicago event, Ramos is sent back to Mexico where he is in custody and awaits prosecution.",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/The_Sergeant_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'The Sergeant #2',
                'series' => 'The Sergeant',
                'tags' => "'The Sergeant'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1743181',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "After Ramos loses someone close to him, he sets his eyes on justice. Only issue, he will need help on this one. With no one left to trust, he has only one option.",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/The_Sergeant_2.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'Blaze And Vigor #1',
                'series' => 'Blaze And Vigor',
                'tags' => "'Blaze And Vigor', 'E.H.V.A'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1768667',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "Henry and Johnny were orphaned at a young age after a mysterious fire burned down their house, killing both their parents. They were later taken in by E.H.V.A., an agency that deals with “special” occurrences. After a multitude of testing, both Henry and Johnny learned that they carried a unique gene in our DNA that scientists still struggle to understand. Henry's gene mysteriously activated the night of the fire, granting him the power to manifest and control fire. Johnny on the other hand had shown no sign of activity and was ruled as “inactive”.",
                'digital_price' => 1.99,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/Blaze_and_Vigor_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'Blaze And Vigor #2',
                'series' => 'Blaze And Vigor',
                'tags' => "'Blaze And Vigor', 'E.H.V.A'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1768669',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "Bent on revenge, Henry is out for blood. Searching every inch of Chicago until he gets his hands on Ramos. But little does Henry know, Ramos is always a step ahead.",
                'digital_price' => 1.99,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/Blaze_and_Vigor_2.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'Blaze And Vigor #3',
                'series' => 'Blaze And Vigor',
                'tags' => "'Blaze And Vigor', 'E.H.V.A'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1768670',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "Crime boss no more, Ramos has his eyes set on a larger goal. It will be up to Henry to stop Ramos from achieving his dream.",
                'digital_price' => 1.99,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/Blaze_and_Vigor_3.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'E.H.V.A #1',
                'series' => 'E.H.V.A',
                'tags' => "'Blaze And Vigor', 'E.H.V.A'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1768671',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "Moon is stranded on an unknown rogue planet and is in need of ship repairs to free her friends and family from Shala, the Anunnaki princess. Meanwhile on earth the heroes at E.H.V.A. are attempting to gather information on the alien relics that have been popping up.",
                'digital_price' => 1.99,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/EHVA_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'E.H.V.A #2',
                'series' => 'E.H.V.A',
                'tags' => "'Blaze And Vigor', 'E.H.V.A'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1768672',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "Moon is stranded on an unknown rogue planet and is in need of ship repairs to free her friends and family from Shala, the Anunnaki princess. Meanwhile on earth the heroes at E.H.V.A. are attempting to gather information on the alien relics that have been popping up.",
                'digital_price' => 1.99,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/EHVA_2.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'E.H.V.A #3',
                'series' => 'E.H.V.A',
                'tags' => "'Blaze And Vigor', 'E.H.V.A'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1768674',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "Enlil has found a new purpose in life, his new destiny! It will be up to E.H.V.A. to put an end to Enlil’s plot.",
                'digital_price' => 1.99,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/EHVA_3.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'E.H.V.A #4',
                'series' => 'E.H.V.A',
                'tags' => "'Blaze And Vigor', 'E.H.V.A'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1768675',
                'ejunkie_link_physical' => null,
                'publisher_id' => 3,
                'summary' => "The epic showdown against Enlil begins now!",
                'digital_price' => 1.99,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/ecru_comics/EHVA_4.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'ecrucomics'
            ],
            [
                'product_name' => 'Operation: Nitro',
                'series' => 'Operation: Nitro',
                'tags' => "'The Alpha', 'Operation: Nitro'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1738407',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => 'Operation: Nitro takes place one month after the events of The Alpha Prototype Trilogy. James (Jim) White former United States Special Forces, is reunited with his former members of his unit and was called once again on a dangerous mission where they need the help of an "enhanced".',
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_operationnitro/covers/Operation_Nitro.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'operationnitro'
            ],
            [
                'product_name' => 'The Alpha #1',
                'series' => 'The Alpha',
                'tags' => "'The Alpha', 'Operation: Nitro'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1721712',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "A new threat of adaptables is terrorizing New York City. Follow Jason Perez (The Alpha) on a journey to find out who's responsible for these recent attacks.",
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_thealpha/covers/The_Alpha_1_Cover.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'thealpha'
            ],
            [
                'product_name' => 'The Alpha #2',
                'series' => 'The Alpha',
                'tags' => "'The Alpha', 'Operation: Nitro'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1721711',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "Continuing the events of The Alpha 1; Jason uncovers the mysteries behind the attacks which leads to an epic showdown with a familiar foe!",
                'digital_price' => 3.99,
                'physical_price' => null,
                'img_string' => 'img/series_thealpha/covers/The_Alpha_2_Cover.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'thealpha'
            ],
            [
                'product_name' => 'The Alpha #3',
                'series' => 'The Alpha',
                'tags' => "'The Alpha', 'Operation: Nitro'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1722133',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "An epic 37 page conclusion to the Prototype Trilogy where the stakes are driven high and heroes are molded through pressure. The Alpha goes head to head with Phantom for the last time, with a new suit and new set of powers!",
                'digital_price' => 3.99,
                'physical_price' => null,
                'img_string' => 'img/series_thealpha/covers/The_Alpha_3_Cover.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'thealpha'
            ],
            [
                'product_name' => 'The Alpha #1 (R)',
                'series' => 'The Alpha',
                'tags' => "'The Alpha', 'Operation: Nitro'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1743143',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "A new threat of adaptables is terrorizing New York City. Follow Jason Perez (The Alpha) on a journey to find out who's responsible for these recent attacks, in this remastered edition of the story that started it all!",
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_thealpha/covers/The_Alpha_1_Remastered_Cover.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'thealpha'
            ],
            [
                'product_name' => 'The Alpha #4',
                'series' => 'The Alpha',
                'tags' => "'The Alpha', 'Operation: Nitro'",
                'ejunkie_link_digital' => '',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "",
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_thealpha/covers/The_Alpha_4_Cover.webp',
                'in_development' => 1,
                'physical_available' => 0,
                'store_slug' => 'thealpha'
            ],
            [
                'product_name' => 'T.S.D.S #1',
                'series' => 'The Super Dragonfly Sentinels',
                'tags' => "'The Super Dragonfly Sentinels'",
                'ejunkie_link_digital' => '',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "Michigan Ramirez, Grayson Lore, and Matthew Sel Basma are the last line of defense for the Kido Galaxy as the invading Alien Race The Alnoe wants to get rid of life across the Kido Galaxy and reign as the only species to survive. Beltox creates The Super Dragonfly Sentinels in which he uses Michigan and Co to transfigure their DNA with Dragonfly ones, in which he creates a superhuman fighting force to combat the alien threat.",
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_TSDS/covers/TSDS_1_Cover.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'tsds'
            ],
            [
                'product_name' => 'Tiny Tokes #1',
                'series' => 'Super Stoner Chronic Rangers',
                'tags' => "'Super Stoner Chronic Ranger'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1743149',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "",
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_chronicrangers/covers/Chronic_Rangers_Tiny_Tokes_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'chronicrangers'
            ],
            [
                'product_name' => 'Tiny Tokes #2',
                'series' => 'Super Stoner Chronic Rangers',
                'tags' => "'Super Stoner Chronic Ranger'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1743150',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "",
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_chronicrangers/covers/Chronic_Rangers_Tiny_Tokes_2.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'chronicrangers'
            ],
            [
                'product_name' => 'Zero_Medal #1',
                'series' => 'Zero_Medal',
                'tags' => "'Zero_Medal'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1724887',
                'ejunkie_link_physical' => null,
                'publisher_id' => 2,
                'summary' => "Garra and Pandora's first adventure. In this issue, Garra, a creature created in an alien laboratory by using a human DNA and a tiger DNA, is sent to planet Earth to kill a young police woman named Pandora and retrieve the Universe Medal she just got from a strange unidentified biker. Mystery surrounds the relationship between the Garra alien creator called Dr. Mente, an old rival known only as Beta and the missing Pandora's brother.",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Zero_Medal/Zero_Medal_Issue_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'zeromedal'
            ],
            [
                'product_name' => 'Zero_Medal #2',
                'series' => 'Zero_Medal',
                'tags' => "'Zero_Medal'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1724889',
                'ejunkie_link_physical' => null,
                'publisher_id' => 2,
                'summary' => "In the second episode of Zero_Medal series, Sombra is sent by Dr. Mente to a mission Garra failed in the previous issue. Garra still has no memory. Amazed with super heroes comic books he decides to protect his beloved by fighting the new enemy. The fight with Sombra will reveal some things about Garra's past.",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Zero_Medal/Zero_Medal_Issue_2.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'zeromedal'
            ],
            [
                'product_name' => 'Zero_Medal #3',
                'series' => 'Zero_Medal',
                'tags' => "'Zero_Medal'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1734074',
                'ejunkie_link_physical' => null,
                'publisher_id' => 2,
                'summary' => "This is the end of the first story arc! Garra comes into conflict with who he was before he met Pandora, with who he is today and with the Garra he will have to decide to be from now on. His decisions will completely change his and everyone's destiny. Pandora continues in her struggle to discover what happened to her brother and his connection to these powerful medals.",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Zero_Medal/Zero_Medal_Issue_3.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'zeromedal'
            ],
            [
                'product_name' => 'Saint #1',
                'series' => 'Saint',
                'tags' => "'Saint'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1724890',
                'ejunkie_link_physical' => null,
                'publisher_id' => 6,
                'summary' => "A nameless vigilante finds himself in a drug warehouse disguised as a construction business, in pursuit of a missing girl. Although the criminals he faces seem outclassed at first, the tables swiftly turn when the hero abruptly makes a horrific discovery. Faced with imminent doom, is it truly the end for the mysterious blue hero… Or is it somehow a new beginning?",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Jrd_comics/Saint_1_Cover.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'saint'
            ],
            [
                'product_name' => 'Saint #2',
                'series' => 'Saint',
                'tags' => "'Saint'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1724891',
                'ejunkie_link_physical' => null,
                'publisher_id' => 6,
                'summary' => "After dying at the hand of one of the city’s most notorious drug lords, Jake Barker awakens in a  mysterious place called the After Realm. Given a second chance at life, it is now his mission to serve the  timeless being coined as “Judge” and re-establish The Balance as the super-powered being known as Saint.",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Jrd_comics/Saint_2_Cover.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'saint'
            ],
            [
                'product_name' => 'Saint #3',
                'series' => 'Saint',
                'tags' => "'Saint'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1724892',
                'ejunkie_link_physical' => null,
                'publisher_id' => 6,
                'summary' => "With a handful of victories under his belt, Saint has adjusted to his new life as a superhero… Or at least so he had thought. When faced with an all-out attack at a busy amusement park, our hero not only learns the hard way that he cannot be everywhere at once, but also that he is perhaps far more vulnerable than he had thought.",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Jrd_comics/Saint_3_Cover.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'saint'
            ],
            [
                'product_name' => 'Saint #4',
                'series' => 'Saint',
                'tags' => "'Saint'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1724894',
                'ejunkie_link_physical' => null,
                'publisher_id' => 6,
                'summary' => "While viewing the Cos-Orb in the After Realm, Judge sees an unsettling image of a dead Saint. Luckily, the real Saint is standing safely beside him. The dead impersonator lures Saint to the scene of the crime, where he finds a hostage situation underway at a comic book convention in his home city of Sprymouth. After mysteriously losing his powers, can Saint manage to save the day, or will the blood of countless innocent cosplayers be on his hands?",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Jrd_comics/Saint_4_Cover.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'saint'
            ],
            [
                'product_name' => 'Saint #5',
                'series' => 'Saint',
                'tags' => "'Saint'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1724895',
                'ejunkie_link_physical' => null,
                'publisher_id' => 6,
                'summary' => "In this gripping final chapter, Saint battles increasingly powerful enemies as he advances through the levels of the convention building. With the odds stacked heavily against him, he must find a way to win and save all the hostages that desperately wait for him on the main floor below. Unfortunately, Saint now feels as powerless as his fans. Will the hero somehow triumph over those who inflict pain on the innocent and get vengeance once and for all?",
                'digital_price' => 3.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Jrd_comics/Saint_5_Cover.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'saint'
            ],
            [
                'product_name' => 'Saint (Vol. 1)',
                'series' => 'Saint',
                'tags' => "'Saint'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1724896',
                'ejunkie_link_physical' => null,
                'publisher_id' => 6,
                'summary' => "Jake Barker always wanted to be a superhero. Acting as a vigilante for years, one day he finally got his wish… Too bad he had to die for it. As the world's first superhero, he is finding that his new life is not all that it's cracked up to be. Now out for vengeance, will his abilities be enough, or will vengeance find him first as he struggles to understand his new life while attempting to maintain The Balance? This volume contains the full compilation of all 5 chapters, plus an epilogue and bonus art!",
                'digital_price' => 12.00,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Jrd_comics/Saint_Full_Story.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'saint'
            ],
            [
                'product_name' => 'Shadow #1',
                'series' => 'Shadow',
                'tags' => "'Shadow'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1738406',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "Jason Lynch has been invited into a new partnership with the mayor of Chicago and the city’s new E.C.U. Advisor Harry Shuester. Suspicious of the new project Jason investigates as the local vigilante (Shadow) only to find out the task may be tougher than expected.",
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_shadow/covers/Shadow_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'shadow'
            ],
            [
                'product_name' => 'Legends #1',
                'series' => 'Legends',
                'tags' => "'Legends', 'Escape The Pit'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1721703',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "Follow Lancelot, the last surviving member of the round table, as he hunts down the monsters that mean to bring an end to the modern world as we know it.",
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_legends/covers/Legends_1.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'legends'
            ],
            [
                'product_name' => 'Legends #2',
                'series' => 'Legends',
                'tags' => "'Legends', 'Escape The Pit'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1734485',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "With the sudden increase of the dead rising around the globe Lancelot must bring an end to Merlin's plans before it's too late.",
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_legends/covers/Legends_2.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'legends'
            ],
            [
                'product_name' => 'Awaken',
                'series' => 'Awaken',
                'tags' => "'Awaken'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1743148',
                'ejunkie_link_physical' => null,
                'publisher_id' => 5,
                'summary' => "What can one kid do, in the face of a corrupt and oppressive world. Well, Zesh is on his way to finding out. Considered a dreamer by most, Zesh is constantly caught up in the worlds beyond his waking life. Zesh is a quick-witted kid, with a strong sense of intuition, empathy, and like most kids his age – sarcasm... And for a kid growing up after the end of the world he also has an exquisite collection of 90’s rap music! Z is a student, growing up in the lower-class district of Fruatia. Though unlike most, he has an opportunity to leave the life he knows behind and embrace a new one amongst the city’s elites and upper-class. However, he is starting to feel that this decision is not an easy one to make. Confronted by the injustice of the world around him, Zesh is guided to forge a new path beyond the stern control of the city – a path of personal empowerment and reconnection to nature.",
                'digital_price' => 7.50,
                'physical_price' => null,
                'img_string' => 'img/other_publishers/Flat_Timez/Awaken_Vol1_cover.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'awaken'
            ],
            [
                'product_name' => 'Godpunk #0',
                'series' => 'Godpunk',
                'tags' => "'Godpunk'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1734068',
                'ejunkie_link_physical' => null,
                'publisher_id' => 7,
                'summary' => "When Connor Thorne, a young archaeology student, takes a mysterious trip to a dig site in Greece he finds himself in the middle of a millennia old conflict. The god Tithonus has chosen Connor to wield the CICADA CHANGER and transform into GODPUNK! Now he faces armed mercenaries, vengeful gods, and many more challenges fit for ancient myth.",
                'digital_price' => 7.50,
                'physical_price' => null,
                'img_string' => 'img/series_godpunk/covers/Godpunk.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'godpunk'
            ],
            [
                'product_name' => 'Broken Realities #1',
                'series' => 'Broken Realities',
                'tags' => "'Broken Realities'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1770873',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => 'With the first universal war coming to end, the Entities break reality by destroying one of their own. The sudden cascade of cosmic energies that were released when Tenebris met her end had broken space itself, resulting in the formation of the three territories that make up the universe as we know it.',
                'digital_price' => 2.99,
                'physical_price' => null,
                'img_string' => 'img/series_brokenrealities/covers/Broken_Realities_1_cover.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'brokenrealities'
            ],
            [
                'product_name' => 'Escape The Pit',
                'series' => 'Escape The Pit',
                'tags' => "'Escape The Pit'",
                'ejunkie_link_digital' => 'https://www.fatfreecartpro.com/ecom/gb.php?&c=cart&ejc=2&cl=382587&i=1721446',
                'ejunkie_link_physical' => null,
                'publisher_id' => 1,
                'summary' => "The world's deadliest monsters have escaped",
                'digital_price' => 1.00,
                'physical_price' => null,
                'img_string' => 'img/series_escapethepit/covers/Escape_The_Pit.webp',
                'in_development' => 0,
                'physical_available' => 0,
                'store_slug' => 'escapethepit'
            ],
        ]);
    }
}
