@extends('layouts.app')
@section('content')
<section>
    <div data-bss-parallax-bg="true" style="height: 300px;background: linear-gradient(rgba(0,0,0,0.17) 6%, #000000 100%), url({{ url('img/br_admin/join_the_fight.webp') }}) center / cover;"></div>
</section>
<section class="contact-clean" style="background: rgb(0,0,0);padding-top: 30px;">
    <h1 class="text-center" style="font-family: 'Open Sans', sans-serif;font-weight: bold;color: rgb(255,255,255);font-size: 40px;">SUBMISSIONS</h1>
    <div class="col-lg-10 align-self-center mx-auto">
        <p class="text-center" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;"><span style="background-color: transparent;">Here at Broken Reality Comics we are actively seeking new indie talent to join the creator-owned team. Thank you for your interest in submitting your work to us, please read our official submission guidelines below.</span></p>
    </div>
    <div class="container">
        <p class="text-center" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;"></p>
        <hr style="color: #ffffff;">
        <h1 style="font-family: 'Open Sans', sans-serif;font-weight: bold;font-size: 25px;"><span style="color: rgb(255, 255, 255);">How to Submit To BRC:</span></h1>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;"><strong><span style="background-color: transparent;">BRC only publishes creator-owned material.</span></strong><span style="background-color: transparent;"> We do not contract creators; we’re only interested in publishing original content for which you would retain all rights.</span></p>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;"><strong><span style="background-color: transparent;">Distribution: Digital VS Physical.</span></strong><span style="background-color: transparent;"> BRC does offer both options, however the terms of which will be discussed with the creators beforehand. We take a small flat fee off the books published and it will be the responsibility of the creators to determine the division of the remaining pay between their creative team members.</span></p>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;"><strong><span style="background-color: transparent;">Things often change from proposal to page.</span></strong><span style="background-color: transparent;"> If the intended title of your book is awkward or unwieldy, we may suggest changing it. If your art style is difficult to follow we may suggest changing it. There have been cases where we’ve designed logos, helped redesign characters, and done cover sketches. However, no changes will be made without creator approval.</span></p>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;margin-bottom: 30px;"><strong><span style="background-color: transparent;">Accepted or Declined.</span></strong><span style="background-color: transparent;"> If we decide to accept your project, a member of our creative team will be in touch via email to schedule a meeting with creators involved to discuss the next step.</span></p>
        <hr style="color: #ffffff;margin-bottom: 30px;">
        <h1 style="font-family: 'Open Sans', sans-serif;font-weight: bold;font-size: 25px;"><span style="color: rgb(255, 255, 255);">Proposal Requirements:</span></h1>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;"><span style="background-color: transparent;">1. A brief, typed </span><strong><span style="background-color: transparent;">cover letter</span></strong><span style="background-color: transparent;"> that summarizes your project. Include contact information (name and email address). Submissions are responded to via e-mail only.</span></p>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;"><span style="background-color: transparent;">2.&nbsp;&nbsp;A typed, one page, </span><strong><span style="background-color: transparent;">synopsis </span></strong><span style="background-color: transparent;">of the overall story arc (not just of the first issue). Please keep this as succinct as possible and do include major plot points and spoilers. Tell us what sets your story apart from other comics. You can tell us whether you see it as a full color or a black-and-white book, a miniseries or an ongoing series, a prestige book or an original graphic novel. There are times, however, when we may suggest what format we think will be most successful for your story in the current market.</span></p>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;"><span style="background-color: transparent;">3.&nbsp;</span><strong><span style="background-color: transparent;">Copies of fully inked and lettered sequential story art pages </span></strong><span style="background-color: transparent;">(any size, but no character sketches or bios). Please include a minimum of five pages that are fully inked and lettered. We may make suggestions based on these, but we are primarily concerned with your understanding of the medium and how to tell a sequential story. </span><strong><span style="background-color: transparent;">Colour is OPTIONAL.</span></strong></p>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;margin-bottom: 30px;"><span style="background-color: transparent;">4.</span><strong><span style="background-color: transparent;">&nbsp;</span></strong><span style="background-color: transparent;">A</span><strong><span style="background-color: transparent;"> cover </span></strong><span style="background-color: transparent;">mock-up, this lets us know whether or not you understand the market and gives us a good barometer on your design sense. With creator approval, this may go through a redesign if we decide to acquire your project.</span></p>
        <hr style="color: #ffffff;margin-bottom: 30px;">
        <h1 style="font-family: 'Open Sans', sans-serif;font-weight: bold;font-size: 25px;"><span style="color: rgb(255, 255, 255);">Things To Keep In Mind:</span></h1>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;"><strong><span style="background-color: transparent;">The creative team in your pitch is the one we expect to see actually working on your book.</span></strong><span style="background-color: transparent;"> If the artist you pitched with leaves the team, you will need to re-submit your proposal with the new creative team line-up. This also means that with all ongoing titles we need to be made aware of and approve all changes to the creative team.</span></p>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;"><strong><span style="background-color: transparent;">Please do not include praise or testimonials</span></strong><span style="background-color: transparent;">. We are only interested in your work as it stands on its own merits.</span></p>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;"><strong><span style="background-color: transparent;">We are not looking for any specific genre of comic book.</span></strong><span style="background-color: transparent;"> We are looking for comics that are well written and well drawn, by people who are dedicated and can meet deadlines. However, we are not looking for stories that are politically driven or overly sexually explicit.</span></p>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;"><span style="background-color: transparent;">Broken Reality Comics </span><strong><span style="background-color: transparent;">owns no intellectual properties</span></strong><span style="background-color: transparent;">, you can be assured accepted or not that your property will remain yours.</span></p>
        <p class="text-start" style="color: rgb(255,255,255);font-family: 'Open Sans', sans-serif;font-size: 14px;margin-bottom: 30px;"><strong><span style="background-color: transparent;">Most Importantly, have fun creating!</span></strong></p>
    </div>
    <form class="text-center border rounded-0" style="background: rgb(0,0,0);">
        <div class="container text-center" style="font-family: 'Open Sans', sans-serif;font-weight: bold;"><label class="form-label text-center" style="font-size: 25px;color: rgb(255,255,255);">Contact Information</label></div><input class="form-control" type="text" placeholder="Full Name" style="margin-bottom: 20px;" required="" minlength="1"><input class="form-control" type="email" placeholder="Email" style="margin-bottom: 20px;" required="" minlength="1">
        <div class="container text-center" style="font-family: 'Open Sans', sans-serif;font-weight: bold;"><label class="form-label text-center" style="font-size: 25px;color: rgb(255,255,255);">File Specifications</label></div>
        <div class="container text-center" style="margin-bottom: 10px;"><small class="form-text" style="color: rgb(255,255,255);">Please ensure that the documents submitted fit the BRC guidelines. Uploaded files must be in a PDF, DOC, PNG, or JPEG format.&nbsp;</small></div><input class="form-control" type="file" style="margin-bottom: 20px;" name="Cover Letter" required="" multiple="">
        <div class="container">
            <div class="form-check text-start" style="margin-bottom: 20px;"><input class="form-check-input" type="radio" id="formCheck-2"><label class="form-check-label" for="formCheck-2" style="color: rgb(255,255,255);">I understand that all the information above is correct and I am the owner of the intellectual properties being submitted.</label></div>
        </div><input class="btn btn-primary" type="submit" name="Submit" style="background: #ffffff;color: rgb(0,0,0);" required="">
    </form>
</section>
@endsection